language: java
sudo: true
dist: trusty
jdk: oraclejdk8

services:
- postgresql


addons:
  hosts:
  - postgres
  apt:
    packages:
    - oracle-java8-installer
before_install:
- chmod a+x ./mvnw


script:
- ./mvnw clean verify
#- ./mvnw clean install -B

#sudo: required
#services:
#- docker

