language: java
sudo: true
dist: trusty
jdk: oraclejdk9
services:
- postgresql

  
addons:
  hosts:
  - postgres
  apt:
    packages:
    - oracle-java9-installer
before_install:
- chmod a+x ./mvnw


script:
- ./mvnw clean install -B

#sudo: required
#services:
#- docker

