language: java
sudo: true
dist: trusty
jdk: oraclejdk8

services:
- postgresql


addons:
  hosts:
  - postgres
  apt:
    packages:
    - oracle-java8-installer
before_install:
- chmod a+x ./mvnw

deploy:
  provider: heroku
  api_key: d03167db-253d-42b0-81e5-67dee90de1ca
  app: apipostgress

script:
#- ./mvnv verify -B
#- ./mvnw  verify
- ./mvnw clean verify install -B

#sudo: required
#services:
#- docker

