version: '3.3'
services:
  web:
    build: .
    container_name: apipostgress
    volumes:
    - ./composeexample:/code
    ports:
    - "8080:8080"
    links:
    - postgres
    depends_on:
    - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  dbdata: