version: 2
jobs:
  build:
    
    working_directory: ~/apipostgress-spring 

    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

    steps:
      - checkout
      - run: mvn test
      - store_artifacts:
          path: target/apipostgress-SNAPSHOT.jar